//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sounds {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MiscStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MiscStrings() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sounds.MiscStrings", typeof(MiscStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Album Artist 的當地語系化字串。
        /// </summary>
        internal static string albumArtist {
            get {
                return ResourceManager.GetString("albumArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0} ({1}) 的當地語系化字串。
        /// </summary>
        internal static string albumArtistPrintf {
            get {
                return ResourceManager.GetString("albumArtistPrintf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 There have been changes made to the playlist. Do you want to save your changes? 的當地語系化字串。
        /// </summary>
        internal static string changeFileWhileDirty {
            get {
                return ResourceManager.GetString("changeFileWhileDirty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 There is a track currently playing. Are you sure you want to stop playing the track and switch to another playlist? 的當地語系化字串。
        /// </summary>
        internal static string changeFileWhilePlaying {
            get {
                return ResourceManager.GetString("changeFileWhilePlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 There is a track currently playing. Are you sure you want to stop playing the track and create a new playlist? 的當地語系化字串。
        /// </summary>
        internal static string newFileWhilePlaying {
            get {
                return ResourceManager.GetString("newFileWhilePlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Paused 的當地語系化字串。
        /// </summary>
        internal static string paused {
            get {
                return ResourceManager.GetString("paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Playing 的當地語系化字串。
        /// </summary>
        internal static string playing {
            get {
                return ResourceManager.GetString("playing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 There is a track currently playing. Are you sure you want to stop playing the track to quit the application? 的當地語系化字串。
        /// </summary>
        internal static string quitWhilePlaying {
            get {
                return ResourceManager.GetString("quitWhilePlaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Stopped 的當地語系化字串。
        /// </summary>
        internal static string stopped {
            get {
                return ResourceManager.GetString("stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Untitled Playlist 的當地語系化字串。
        /// </summary>
        internal static string untitledPlaylist {
            get {
                return ResourceManager.GetString("untitledPlaylist", resourceCulture);
            }
        }
    }
}
